function Hd = Eigen1
%EIGEN1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 28-Nov-2019 13:44:13

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N     = 90;   % Order
Fpass = 0.3;  % Passband Frequency
Fstop = 0.4;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 1;    % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

fvtool(Hd);

%Done by SRI HARSHA VADATHYA(170108037) - EE320 Assignment
% [EOF]
